[package]
name = "common"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
name = "common"

[features]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "1.0.2" }
spl-token-2022 = { version = ">=10.0.0, <11", features = ["no-entrypoint"] }
bytemuck = { version = "1.17", features = ["derive", "min_const_generics"] }


[dev-dependencies]
deploy           = { path = "../deploy",           features = ["cpi"] }
deactivate       = { path = "../deactivate",       features = ["cpi"] }
mint             = { path = "../mint",             features = ["cpi"] }
operations       = { path = "../operations",       features = ["cpi"] }
freeze           = { path = "../freeze",           features = ["cpi"] }
metadata-update  = { path = "../metadata-update",  features = ["cpi"] }
pause            = { path = "../pause",            features = ["cpi"] }
transfer-control = { path = "../transfer-control", features = ["cpi"] }
transfer         = { path = "../transfer",         features = ["cpi"] }
transfer-hook    = { path = "../transfer-hook",    features = ["cpi"] }
snapshot         = { path = "../snapshot",         features = ["cpi"] }
bond             = { path = "../bond",             features = ["cpi"] }
coupon           = { path = "../coupon",           features = ["cpi"] }
treasury         = { path = "../treasury",         features = ["cpi"] }
factory          = { path = "../factory",          features = ["cpi"] }

[lints.rust]
unexpected_cfgs = { level = "allow" }
